"""table vacancies

Revision ID: 3531cb475146
Revises: f38657094266
Create Date: 2026-08-29 09:41:59.256256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3531cb475146'
down_revision: Union[str, Sequence[str], None] = 'f38657094266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_entity', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['id_entity'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_confirmations', schema=None) as batch_op:
        batch_op.alter_column('resend_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_confirmations', schema=None) as batch_op:
        batch_op.alter_column('resend_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True)

    op.drop_table('vacancies')
    # ### end Alembic commands ###
