"""update vacancy modality

Revision ID: 5c3a37e8d380
Revises: 3531cb475146
Create Date: 2026-09-12 14:11:34.221439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3a37e8d380'
down_revision: Union[str, Sequence[str], None] = '3531cb475146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modality', sa.Enum('REMOTE', 'IN_PERSON', name='vacancymodality'), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('thoroughfare', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('details', sa.String(length=100), nullable=True))
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('uf',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.drop_column('location')

    op.execute("UPDATE vacancies SET modality = 'REMOTE' WHERE modality IS NULL")

    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.alter_column(
            'modality',
            existing_type=sa.Enum('REMOTE', 'IN_PERSON', name='vacancymodality'),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('uf',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('details')
        batch_op.drop_column('thoroughfare')
        batch_op.drop_column('number')
        batch_op.drop_column('cep')
        batch_op.drop_column('modality')

    # ### end Alembic commands ###
