"""create invitations table

Revision ID: 70562aa40200
Revises: d7c81a4e69b2
Create Date: 2026-09-21 13:10:34.161876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70562aa40200'
down_revision: Union[str, Sequence[str], None] = 'd7c81a4e69b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='invitationstatus'), nullable=False),
    sa.Column('invitation_type', sa.Enum('ENTITY', 'VACANCY', 'FRIEND', name='invitationtype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ANIMALS', 'ENVIRONMENT', 'EDUCATION', 'HEALTH', 'SOCIAL_ASSISTANCE', 'ELDERLY', 'CHILDREN_AND_TEENS', 'INCLUSION', 'CULTURE_AND_ART', 'SPORTS', 'TECHNOLOGY', 'HUMANITARIAN_AID', 'COMMUNITY', 'EVENTS', name='vacancybranch'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.Enum('ANIMALS', 'ENVIRONMENT', 'EDUCATION', 'HEALTH', 'SOCIAL_ASSISTANCE', 'ELDERLY', 'CHILDREN_AND_TEENS', 'INCLUSION', 'CULTURE_AND_ART', 'SPORTS', 'TECHNOLOGY', 'HUMANITARIAN_AID', 'COMMUNITY', 'EVENTS', name='vacancybranch'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.drop_table('invitations')
    # ### end Alembic commands ###
