"""Inital migration

Revision ID: 9c6adc0f5c48
Revises:
Create Date: 2026-07-21 11:42:41.836313

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c6adc0f5c48"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entidades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("nome_usuario", sa.String(), nullable=False),
        sa.Column("ramo", sa.String(), nullable=False),
        sa.Column("descricao", sa.String(), nullable=False),
        sa.Column("cidade", sa.String(), nullable=False),
        sa.Column("uf", sa.String(), nullable=False),
        sa.Column("criado_em", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome_usuario"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("senha", sa.String(), nullable=False),
        sa.Column("data_nasc", sa.Date(), nullable=False),
        sa.Column("cidade", sa.String(), nullable=False),
        sa.Column("uf", sa.String(), nullable=False),
        sa.Column("confirmado", sa.Boolean(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.Column("foto_perfil", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
    )
    op.create_table(
        "confirmacoes_email",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("criado_em", sa.TIMESTAMP(), nullable=False),
        sa.Column("expiracao", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "membros_entidade",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("id_entidade", sa.Integer(), nullable=False),
        sa.Column(
            "cargo", sa.Enum("admin", "editor", "membro", name="cargomembro"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["id_entidade"],
            ["entidades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("membros_entidade")
    op.drop_table("confirmacoes_email")
    op.drop_table("usuarios")
    op.drop_table("entidades")
    # ### end Alembic commands ###
