"""create initial tables

Revision ID: 9c7322c9df95
Revises: 
Create Date: 2026-08-17 16:43:10.073631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7322c9df95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('confirmed_email', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('admin_system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('email_confirmations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('hash_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('expire_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_confirmations_hash_token'), ['hash_token'], unique=True)

    op.create_table('members_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_entity', sa.Integer(), nullable=False),
    sa.Column('position', sa.Enum('admin', 'editor', 'member', name='member_position', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['id_entity'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members_entities', schema=None) as batch_op:
        batch_op.create_index('uq_member_user_entity', ['id_user', 'id_entity'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members_entities', schema=None) as batch_op:
        batch_op.drop_index('uq_member_user_entity')

    op.drop_table('members_entities')
    with op.batch_alter_table('email_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_confirmations_hash_token'))

    op.drop_table('email_confirmations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('entities')
    # ### end Alembic commands ###
