"""add resend_at to email confirmations

Revision ID: f38657094266
Revises: 9c7322c9df95
Create Date: 2026-08-19 11:53:52.819181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38657094266'
down_revision: Union[str, Sequence[str], None] = '9c7322c9df95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_confirmations') as batch_op:
        batch_op.add_column(
            sa.Column("resend_at", sa.TIMESTAMP(timezone=True), nullable=True,)
        )
    op.execute(
        """
        UPDATE email_confirmations
        SET resend_at = CURRENT_TIMESTAMP
        WHERE resend_at IS NULL

        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_confirmations', schema=None) as batch_op:
        batch_op.drop_column('resend_at')

    # ### end Alembic commands ###
